version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/accesscare
      - OCR_SERVICE_URL=http://ocr-service:5001
    depends_on:
      - mongo
      - ocr-service
    networks:
      - accesscare-network

  ocr-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.ocr
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
    networks:
      - accesscare-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - accesscare-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - accesscare-network

volumes:
  mongo-data:

networks:
  accesscare-network:
    driver: bridge
